# Generated by Django 2.2.4 on 2021-04-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210402_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='notes',
            new_name='email',
        ),
    ]
